// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOOf0PG0wHJZD0-xTW7V7jweQc83i5mgQ',
    appId: '1:770288966254:web:25fcca7966889f6ec4247f',
    messagingSenderId: '770288966254',
    projectId: 'thuri-cycle',
    authDomain: 'thuri-cycle.firebaseapp.com',
    storageBucket: 'thuri-cycle.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbKKu4FW6hkNSC0JHqeibqawLRRhT3cpE',
    appId: '1:770288966254:android:1b9c98f9c525888bc4247f',
    messagingSenderId: '770288966254',
    projectId: 'thuri-cycle',
    storageBucket: 'thuri-cycle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyw6FYoDEQV6glZUkjJgjIoTRmWa1h7sU',
    appId: '1:770288966254:ios:a4fcd88cd82a18dac4247f',
    messagingSenderId: '770288966254',
    projectId: 'thuri-cycle',
    storageBucket: 'thuri-cycle.firebasestorage.app',
    androidClientId: '770288966254-ictc3142usrd5q8kdpmlmmvo4jhaodpo.apps.googleusercontent.com',
    iosClientId: '770288966254-pa83r0khghqufdte8klfrtn5ne8166gv.apps.googleusercontent.com',
    iosBundleId: 'com.roosnoff.thuricycle.thuri-cycle',
  );

}